version: '3.1'
services:
  challenge_app:
    container_name: itau-challenge
    image: springboot-postgresql
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - compose_db
    networks:
      - itauchallenge
    restart: always

  compose_db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service_challenge_db
    networks:
      - itauchallenge
    restart: always

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local

networks:
  itauchallenge:
    driver: bridge