version: '3.1'
services:
  challenge_app:
    container_name: itau-challenge_app
    image: springboot-postgresql
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - compose_db
      - zookeeper
      - kafka
    restart: always

  compose_db:
    container_name: itau-challenge_db
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service_challenge_db
    restart: always

  zookeeper:
    container_name: itau-challenge_zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: itau-challenge_kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092


volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local

networks:
  itauchallenge:
    driver: bridge