spring:
  application: itau-challenge
  datasource:
    url: jdbc:postgresql://compose_db:5432/service_challenge_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show-sql: true
        format_sql: true
        jdbc:
            lob:
              non_contextual_creation: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: group-id

springdoc:
  swagger-ui:
    tagsSorter: alpha

auto:
  create:
    topics:
      enable: true

itauchallenge:
  jwt:
    secret: 2068ed5b-c591-4fb1-b9a2-2ec47ab41bf4
    expiration: 600000
  api-docs:
    apiName: Itau Challenge API
    description: API Developed for the Itau Backend Challenge
    version: '@project.version@'
    contact:
      name: Wilton Souza
      url: https://github.com/8bitbeard
      email: willsouzafilho@gmail.com